[book]
language = "uk"
multilingual = false
src = "docs"

# Замініть авторство проєкта на своє
authors = ["Sergey Bykovets"]

# Змініть назву проєкта на свою
title = "Система аналізу медіа-контенту"

[preprocessor.plantuml]
plantuml-cmd = "plantuml"
use-data-uris = true
